"""Public copy quality checks and repair prompts for unified digests."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from aurora.ai.ranker import LLMAnalysis, LLMRanker, item_prompt_payload
from aurora.config import AIConfig
from aurora.modes.scholar.display import format_paper_description
from aurora.modes.tech_news.notes import display_tech_news_summary
from aurora.models import SignalItem
from aurora.pipeline import StageContext
from aurora.public_copy import is_deterministic_repo_evidence, raw_repo_value


@dataclass(frozen=True)
class PublicCopyQuality:
    """Result of validating the public text that will be rendered."""

    ok: bool
    text: str
    reasons: list[str]


@dataclass(frozen=True)
class PublicDigestAudit:
    """Result of validating the rendered public digest."""

    ok: bool
    reasons: list[str]


SOURCE_COVERS_PATTERN = re.compile(r"\bcovers\b.{0,180}\bwith\b", re.IGNORECASE)
MARKDOWN_HEADING_PATTERN = re.compile(r"(^|\s)#{1,6}\s+\S")
MARKDOWN_LINK_PATTERN = re.compile(r"\[[^\]]+\]\([^)]*$")
EMPHASIS_OR_BULLET_PATTERN = re.compile(r"(^|\s)(?:[*-]\s+|\*\*[^*]+\*\*)")
RELEASE_NOTES_PATTERN = re.compile(r"\bRelease Notes\b")
RAW_ABSTRACT_PATTERN = re.compile(r"^(?:we introduce|we propose|we present|in this paper)", re.IGNORECASE)
PUBLIC_RUN_ID_PATTERN = re.compile(r"\brun-\d{8}t\d{6}z\b", re.IGNORECASE)
DANGLING_ENDINGS = (
    " who need.",
    " they enable.",
    " a vs.",
    " b vs.",
    " and.",
    " or.",
    " of.",
    " to.",
    " for.",
    " from.",
    " by.",
    " as.",
    " in.",
    " on.",
    " with.",
    " that.",
    " which.",
    " and then.",
    " because.",
    " with.",
    " similar i.",
)
ALLOWED_SHORT_FINAL_WORDS = {"ai", "ml", "rl", "ui", "ux", "os", "go", "js", "m3"}
RENDERED_FORBIDDEN_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("source_covers_template", SOURCE_COVERS_PATTERN),
    ("raw_markdown_updates", re.compile(r"\bupdates\s+#", re.IGNORECASE)),
    ("release_note_remnant", RELEASE_NOTES_PATTERN),
    ("deterministic_repo_evidence", re.compile(r"concrete learning evidence", re.IGNORECASE)),
    ("generic_scholar_fallback", re.compile(r"Relevant ML research candidate", re.IGNORECASE)),
    ("public_run_id", PUBLIC_RUN_ID_PATTERN),
    ("generated_run_id", re.compile(r"Generated by Aurora from run", re.IGNORECASE)),
    ("visible_diagnostics", re.compile(r"\b(?:Run diagnostics|Run Summary|Source Health)\b", re.IGNORECASE)),
    ("visible_evidence_block", re.compile(r"\b(?:Evidence|Files|Study|Learn|Connections):", re.IGNORECASE)),
    ("score_visible", re.compile(r"\b\d+(?:\.\d+)?/10\b")),
    ("deterministic_news_template", re.compile(r"\bThe (?:update describes|release highlights)\b", re.IGNORECASE)),
    ("deterministic_news_generic", re.compile(r"This item points to a practical AI tooling or research update", re.IGNORECASE)),
    (
        "generic_hackernews_template",
        re.compile(
            r"(?:This Hacker News story is drawing .+ developer attention|"
            r"Developers are discussing .+ with .+ signal for)",
            re.IGNORECASE,
        ),
    ),
    ("deterministic_repo_template", re.compile(r"is useful for studying how a real project organizes its architecture", re.IGNORECASE)),
    ("deterministic_paper_template", re.compile(r"This paper studies .+ and why the idea could matter for practical AI systems", re.IGNORECASE)),
)


def public_copy_quality(item: SignalItem) -> PublicCopyQuality:
    """Validate the text visible for one selected digest item."""
    text = _public_text(item)
    normalized = " ".join(text.split())
    lowered = normalized.lower()
    # A news summary can be discarded by the renderer, but malformed source
    # summaries still need repair before selection. The other news fields are
    # only checked when they become the rendered text above.
    source_summary = " ".join(str(item.summary or "").split()) if item.type == "news" else ""
    quality_texts = tuple(value for value in (normalized, source_summary) if value)
    quality_lowered = "\n".join(quality_texts).lower()
    reasons: list[str] = []

    for reason, pattern in RENDERED_FORBIDDEN_PATTERNS:
        if any(pattern.search(value) for value in quality_texts):
            reasons.append(reason)

    if len(normalized) < 20:
        reasons.append("too_short")
    if (
        item.type == "news"
        and _has_incomplete_source_sentence(item.summary)
        and normalized == source_summary
    ):
        reasons.append("incomplete_source_sentence")
    if any(SOURCE_COVERS_PATTERN.search(value) for value in quality_texts):
        reasons.append("source_covers_template")
    if "updates #" in quality_lowered or any(
        MARKDOWN_HEADING_PATTERN.search(value) for value in quality_texts
    ):
        reasons.append("raw_markdown")
    if any(MARKDOWN_LINK_PATTERN.search(value) for value in quality_texts):
        reasons.append("broken_markdown")
    if any(_has_duplicated_title_prefix(item, value) for value in quality_texts):
        reasons.append("duplicated_title_prefix")
    if any(_mostly_repeats_title(item, value) for value in quality_texts):
        reasons.append("title_restatement")
    if any(_has_dangling_fragment(value) for value in quality_texts):
        reasons.append("dangling_fragment")
    if any(
        RELEASE_NOTES_PATTERN.search(value) or EMPHASIS_OR_BULLET_PATTERN.search(value)
        for value in quality_texts
    ):
        reasons.append("release_note_remnant")
    if item.type == "news" and re.search(
        r"\bThe (?:update describes|release highlights)\b", quality_lowered, re.IGNORECASE
    ):
        reasons.append("deterministic_news_template")
    if item.type == "news" and (
        "this item points to a practical ai tooling or research update" in quality_lowered
    ):
        reasons.append("deterministic_news_generic")
    if item.type == "news" and re.search(
        r"(?:\bThis Hacker News story is drawing\b.+\bdeveloper attention\b|"
        r"\bDevelopers are discussing\b.+\bwith\b.+\bsignal for\b)",
        quality_lowered,
        re.IGNORECASE,
    ):
        reasons.append("generic_hackernews_template")
    if item.type == "repo" and is_deterministic_repo_evidence(normalized):
        reasons.append("deterministic_repo_evidence")
    source_text = " ".join(
        str(value or "")
        for value in (item.summary, item.why_it_matters, item.learning_value, item.raw_content)
    ).lower()
    if (
        "relevant ml research candidate" in lowered
        or "today's scholar radar" in lowered
        or "relevant ml research candidate" in source_text
        or "today's scholar radar" in source_text
    ):
        reasons.append("generic_scholar_fallback")
    if _looks_like_truncated_raw_abstract(item, normalized):
        reasons.append("truncated_raw_abstract")
    if item.type == "paper" and RAW_ABSTRACT_PATTERN.search(normalized):
        reasons.append("raw_abstract_voice")

    reasons = list(dict.fromkeys(reasons))
    return PublicCopyQuality(ok=not reasons, text=normalized, reasons=reasons)


def audit_rendered_public_digest(markdown: str, web_html: str = "") -> PublicDigestAudit:
    """Validate rendered public Markdown/HTML before delivery."""
    # Source titles are linked in both renderings. They are source-provided
    # names, not generated copy or internal labels.
    markdown = re.sub(r"\[[^\]]+\]\([^\n)]*\)", "", markdown)
    web_html = re.sub(r"<a\b[^>]*>.*?</a>", "", web_html, flags=re.IGNORECASE | re.DOTALL)
    text = "\n".join(part for part in (markdown, web_html) if part)
    normalized = " ".join(text.split())
    reasons: list[str] = []
    for reason, pattern in RENDERED_FORBIDDEN_PATTERNS:
        if pattern.search(normalized):
            reasons.append(reason)
    if _has_dangling_fragment(normalized):
        reasons.append("dangling_fragment")
    return PublicDigestAudit(ok=not reasons, reasons=list(dict.fromkeys(reasons)))


class PublicCopyRepairer:
    """Repair selected public digest text through the existing bounded AI path."""

    def __init__(self, ai_config: AIConfig, *, client: Any | None = None) -> None:
        self.ranker = LLMRanker(ai_config, weights=_repair_weights(), client=client, task="repair")

    async def repair(self, item: SignalItem, context: StageContext) -> SignalItem | None:
        """Return an AI-repaired item, or ``None`` when AI is unavailable/budget-skipped."""
        analyses = await self.ranker.analyze_items([item], _repair_prompt, context)
        analysis = analyses.get(item.id)
        if analysis is None:
            return None
        return apply_public_copy_repair(item, analysis)


def apply_public_copy_repair(item: SignalItem, analysis: LLMAnalysis) -> SignalItem:
    """Apply a repair response to the public fields for one item."""
    summary = _clean_public_sentence(analysis.summary)
    why = _clean_public_sentence(analysis.why_it_matters)
    learning = _clean_public_sentence(analysis.learning_value)

    if item.type == "news":
        public = summary or why or learning
        return item.model_copy(
            update={
                "summary": public or item.summary,
                "why_it_matters": public or item.why_it_matters,
            }
        )
    if item.type == "repo":
        public = why or summary or learning
        return item.model_copy(
            update={
                "why_it_matters": public or item.why_it_matters,
                "summary": summary or item.summary,
            }
        )
    public = summary or why or learning
    return item.model_copy(
        update={
            "summary": public or item.summary,
            "why_it_matters": why or item.why_it_matters,
        }
    )


def _has_duplicated_title_prefix(item: SignalItem, text: str) -> bool:
    if ":" not in text:
        return False
    title = _normalized_words(item.title)
    prefix, remainder = text.split(":", 1)
    return (
        bool(title)
        and _normalized_words(prefix) == title
        and (
            _normalized_words(remainder).startswith(title)
            or len(_normalized_words(remainder).split()) >= 4
        )
    )


def _has_dangling_fragment(text: str) -> bool:
    stripped = text.strip()
    if _has_unbalanced_delimiters(stripped) or _has_short_trailing_sentence(stripped):
        return True
    lowered = stripped.lower()
    if lowered.endswith(DANGLING_ENDINGS):
        return True
    words = re.findall(r"[a-z0-9]+", lowered)
    if words and len(words[-1]) <= 2 and words[-1] not in ALLOWED_SHORT_FINAL_WORDS:
        return True
    return lowered.endswith((" vs.", " e.g.", " i.e."))


def _has_unbalanced_delimiters(text: str) -> bool:
    return (
        text.count("(") > text.count(")")
        or text.count("[") > text.count("]")
        or text.count("{") > text.count("}")
    )


def _has_short_trailing_sentence(text: str) -> bool:
    sentences = [sentence.strip() for sentence in re.split(r"(?<=[.!?])\s+", text) if sentence.strip()]
    if len(sentences) < 2:
        return False
    words = re.findall(r"[A-Za-z0-9]+", sentences[-1])
    all_words = re.findall(r"[A-Za-z0-9]+", text)
    return 0 < len(words) <= 2 and len(all_words) > 6


def _has_incomplete_source_sentence(value: object) -> bool:
    text = str(value or "").strip()
    words = re.findall(r"[A-Za-z0-9]+", text)
    return len(words) >= 5 and not text.endswith((".", "!", "?"))


def _mostly_repeats_title(item: SignalItem, text: str) -> bool:
    if item.type != "news":
        return False
    title_words = _normalized_words(item.title).split()
    text_words = _normalized_words(text).split()
    if len(title_words) < 3 or len(text_words) < 3:
        return False
    if text_words[: len(title_words)] == title_words:
        return True
    title_set = set(title_words)
    overlap = sum(1 for word in text_words[: max(len(title_words) + 4, 8)] if word in title_set)
    return overlap / max(1, len(title_set)) >= 0.85 and len(text_words) <= len(title_words) + 8


def _normalized_words(value: object) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9]+", " ", str(value or "").lower())).strip()


def _public_text(item: SignalItem) -> str:
    if item.type == "news":
        # The renderer applies its own low-quality fallback rules. Validate that
        # exact public result here so a selected item cannot pass this gate with
        # stale raw copy and fail only after rendering.
        return display_tech_news_summary(item)
    if item.type == "paper":
        return format_paper_description(item)
    if item.type == "repo":
        return _repo_public_text(item)
    return raw_repo_value(item)


def _repo_public_text(item: SignalItem) -> str:
    metadata = item.metadata
    for candidate in (metadata.get("description"), item.summary, item.raw_content):
        text = " ".join(str(candidate or "").split()).strip()
        if text:
            return text
    return raw_repo_value(item)


def _looks_like_truncated_raw_abstract(item: SignalItem, text: str) -> bool:
    if item.type != "paper" or not text.endswith("..."):
        return False
    metadata = item.metadata
    if item.summary or metadata.get("semantic_scholar_tldr"):
        return False
    raw = " ".join(str(item.raw_content or "").split())
    if not raw:
        return False
    technical_markers = (
        "typically follow",
        "paradigm",
        "we propose",
        "we present",
        "we introduce",
        "experiments show",
        "state-of-the-art",
    )
    return raw.startswith(text[:-3].strip()[:80]) or any(
        marker in raw.lower() for marker in technical_markers
    )


def _repair_prompt(item: SignalItem) -> tuple[str, str]:
    type_instruction = {
        "news": (
            "Write one concise sentence summarizing the concrete news. Do not start with "
            "a source name, do not say 'covers', and do not include Markdown."
        ),
        "repo": (
            "Write one or two concise Value sentences explaining what a developer or "
            "student can learn from this repository. Do not list stars, forks, license, "
            "homepage, or evidence strings."
        ),
        "paper": (
            "Write one or two student-friendly sentences explaining the idea and why it "
            "could matter in practice. Avoid raw abstract phrasing and unexplained jargon."
        ),
    }.get(item.type, "Write concise public digest copy.")
    system_prompt = (
        "You repair public copy for Aurora, a daily AI learning radar. Return strict JSON "
        "with keys score, summary, why_it_matters, learning_value, action_items, "
        "suggested_learning_path, and tags. Keep public copy polished, factual, and short."
    )
    user_prompt = json.dumps(
        {
            "task": type_instruction,
            "item": json.loads(item_prompt_payload(item)),
            "bad_public_text": _public_text(item),
            "forbidden_patterns": [
                "Source covers Title, with...",
                "updates #",
                "concrete learning evidence",
                "Relevant ML research candidate",
                "raw Markdown headings",
                "public labels such as Evidence:, Files:, Study:, Learn:, or Connections:",
                "Title: title...",
                "dangling endings such as 'and.' or 'Similar i.'",
            ],
        },
        sort_keys=True,
        default=str,
    )
    return system_prompt, user_prompt


def _clean_public_sentence(value: str) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    return text.strip(" \t\r\n-")


def _repair_weights():
    from aurora.config import FinalScoreWeights

    return FinalScoreWeights(deterministic=1.0, llm=0.0)
